CREATE SEQUENCE SEQ_CUSTOMER MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_AUTHORS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_EVENTS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_SPONSORS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_ROOMS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_CUS_EXH MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_AUTH_SEM MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_BOOKS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_BOOK_INV MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_RESERVATION MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_RENTAL_SERV MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_TOPICS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_INVOICE MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_PAYMENTS MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE SEQ_EMPLOYEE MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;